name: Go CICD
on: 
  push: 
    branches: [ main ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with: 
        go-version: '1.17'
    - name: Install Dependencies 
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build 
      run: go build .
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    - name: format go code
      run: go fmt .

    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      with: 
        status: ${{ job.status }}
        fields: repo,message,commit,author,eventName,ref,workflow,job,took
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
  
      